# Compile-time availability only. Runtime factories validate hardware and plugins.
set(KVMUX_JETSON_ENCODER "AUTO" CACHE STRING "Jetson GStreamer encoder: AUTO, ON, or OFF")
set(KVMUX_VIDEOTOOLBOX "AUTO" CACHE STRING "VideoToolbox decoder: AUTO, ON, or OFF")
foreach(option_name KVMUX_JETSON_ENCODER KVMUX_VIDEOTOOLBOX)
    set_property(CACHE ${option_name} PROPERTY STRINGS AUTO ON OFF)
    if(NOT "${${option_name}}" MATCHES "^(AUTO|ON|OFF)$")
        message(FATAL_ERROR "${option_name} must be AUTO, ON, or OFF (got '${${option_name}}')")
    endif()
endforeach()

set(KVMUX_HAS_JETSON_ENCODER 0)
if(NOT KVMUX_JETSON_ENCODER STREQUAL "OFF")
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        if(KVMUX_JETSON_ENCODER STREQUAL "ON")
            find_package(PkgConfig QUIET)
            if(NOT PkgConfig_FOUND)
                message(FATAL_ERROR "KVMUX_JETSON_ENCODER=ON requires PkgConfig and GStreamer core/app/video development packages")
            endif()
            pkg_check_modules(KVMUX_GSTREAMER QUIET IMPORTED_TARGET gstreamer-1.0 gstreamer-app-1.0 gstreamer-video-1.0)
            if(NOT KVMUX_GSTREAMER_FOUND)
                message(FATAL_ERROR "KVMUX_JETSON_ENCODER=ON requires GStreamer core/app/video development packages (gstreamer-1.0, gstreamer-app-1.0, gstreamer-video-1.0)")
            endif()
        else()
            find_package(PkgConfig QUIET)
            if(PkgConfig_FOUND)
                pkg_check_modules(KVMUX_GSTREAMER QUIET IMPORTED_TARGET gstreamer-1.0 gstreamer-app-1.0 gstreamer-video-1.0)
            endif()
        endif()
        if(KVMUX_GSTREAMER_FOUND)
            set(KVMUX_HAS_JETSON_ENCODER 1)
        endif()
    elseif(KVMUX_JETSON_ENCODER STREQUAL "ON")
        message(FATAL_ERROR "KVMUX_JETSON_ENCODER=ON is supported only on Linux")
    endif()
endif()

set(KVMUX_HAS_VIDEOTOOLBOX 0)
if(NOT KVMUX_VIDEOTOOLBOX STREQUAL "OFF")
    if(APPLE)
        find_library(KVMUX_VIDEOTOOLBOX_FRAMEWORK VideoToolbox)
        find_library(KVMUX_COREFOUNDATION_FRAMEWORK CoreFoundation)
        if(KVMUX_VIDEOTOOLBOX_FRAMEWORK AND KVMUX_COREFOUNDATION_FRAMEWORK)
            set(KVMUX_HAS_VIDEOTOOLBOX 1)
        elseif(KVMUX_VIDEOTOOLBOX STREQUAL "ON")
            message(FATAL_ERROR "KVMUX_VIDEOTOOLBOX=ON requires VideoToolbox and CoreFoundation frameworks")
        endif()
    elseif(KVMUX_VIDEOTOOLBOX STREQUAL "ON")
        message(FATAL_ERROR "KVMUX_VIDEOTOOLBOX=ON is supported only on Apple platforms")
    endif()
endif()

message(STATUS "KVMux codec backends: Jetson=${KVMUX_HAS_JETSON_ENCODER}, VideoToolbox=${KVMUX_HAS_VIDEOTOOLBOX}")
